<?php
require_once __DIR__.'/layout/head.phtml';
?>

<?php
require_once __DIR__.'/layout/header.phtml';
?>

	<!-- Begin page content -->
	<main role="main" class="container">
    	<h1 class="mt-5">taskboard to kanboard</h1>
    	<a href="<?= $BASE ?>/migrate"> migrate </a> <br/>
    	<a href="<?= $BASE ?>/priority"> priority </a>
	</main>

<?php
require_once __DIR__.'/layout/footer.phtml';
?>

<?php
require_once __DIR__.'/layout/foot.phtml';
?>
