<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
<!-- 	<link rel="icon" href="favicon.ico"> -->
	<link rel="icon" href="data:;base64,iVBORw0KGgo=">
	
	<title><?= $PAGE["title"] ?></title>
	
	<link href="<?= $BASE ?>/vendor/twbs/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="<?= $BASE ?>/vendor/components/jqueryui/themes/base/jquery-ui.min.css" rel="stylesheet">
	
	<!-- Custom styles for this template -->
	<link href="<?= $BASE ?>/assets/index.css" rel="stylesheet">
	<link rel="shortcut icon" href="#" />
</head>

<body>
